admin.username =Admin
admin.password =admin123
DEFAULT_WAIT=10
#Browser Type > Chrome, Firefox, Edge, Safari
browser=Chrome

#Execution Type > Local, Remote(Headless), LocalHeadless
executionType=Local



base.url =https://opensource-demo.orangehrmlive.com
BASE_API =https://opensource-demo.orangehrmlive.com/web/index.php/api/v2


